### ISSUE TITLE
拡張読み込みを起動後にやると失敗するケースがある

### ISSUE THREAD

**Issue by kuuote** [kuuote/lspoints#3]
恐らく読み込みタイミングが前後するので拡張機能で設定すると反映されないことがある

**Comment by Shougo** [comment]
skkeletonで似たようなエラーが出ていたと思うので原因は同じかと

**Comment by kuuote** [comment]
https://github.com/kuuote/lspoints/commit/f1bf28471589ce55780efb188350775fbf1c9dbe
原因の推測はできるが自環境で再現しないので様子見

**Comment by kuuote** [comment]
大丈夫そう
